id: 03.01_ny-taxi-data-upload-to-gcs
namespace: zoomcamp.hw03

inputs:
  - id: taxi
    type: SELECT
    displayName: Select taxi type
    values:
      - green
      - yellow
    defaults: yellow

variables:
  file_type: "parquet"
  file: "{{ inputs.taxi }}_tripdata_{{ trigger.date | date('yyyy-MM') }}.{{ vars.file_type }}"
  url: "https://d37ci6vzurychx.cloudfront.net/trip-data/{{ render(vars.file) }}"
  gcs_in_file: "{{ outputs.extract.outputFiles[render(vars.file)] }}"
  gcs_out_file: "gs://{{ kv('GCP_BUCKET_NAME') }}/hw03/{{ vars.file }}"


tasks:
  - id: set_label
    type: io.kestra.plugin.core.execution.Labels
    labels:
      file: "{{ render(vars.file) }}"
      taxi: "{{ inputs.taxi }}"
      date: "{{ trigger.date | date('YYYY-MM') }}"
      # gcs_file: "{{ render(vars.gcs_file) }}"

  - id: extract
    type: io.kestra.plugin.scripts.shell.Commands
    outputFiles:
      - "*.{{ vars.file_type }}"
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
    commands:
      - wget --quiet --output-document {{ vars.file }} {{ vars.url }}

  - id: parce_params_debug
    type: io.kestra.plugin.core.log.Log
    logLevel: DEBUG
    message: |
      Параметры для запуска закачки факлв в GCS:
         upload_from: {{ render(vars.gcs_in_file) }}
         upload_to: {{ render(vars.gcs_out_file) }}

  - id: upload_gcs
    type: io.kestra.plugin.gcp.gcs.Upload
    from: "{{ render(vars.gcs_in_file) }}"
    to: "{{ render(vars.gcs_out_file) }}"
    allowFailure: true

  - id: clean_files
    type: io.kestra.plugin.core.storage.PurgeCurrentExecutionFiles
    description: To avoid cluttering your storage, we will remove the downloaded files
  
pluginDefaults:
  - type: io.kestra.plugin.gcp
    values:
      serviceAccount: "{{kv('GCP_CREDS')}}"
      projectId: "{{kv('GCP_PROJECT_ID')}}"
      location: "{{kv('GCP_LOCATION')}}"
      bucket: "{{kv('GCP_BUCKET_NAME')}}"

triggers:
  - id: green_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 12 5 * *"
    inputs:
      taxi: green

  - id: yellow_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 12 5 * *"
    inputs:
      taxi: yellow